version: '3.4'
services:
  bitcoind:
    image: lncm/bitcoind:v23.0
    volumes:
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf

  lnd-alice:
    restart: unless-stopped
    image: lightninglabs/lnd:v0.14.3-beta
    depends_on:
      - bitcoind
    volumes:
      - ./lnd.conf:/root/.lnd/lnd.conf
      - lnd-alice:/cfg
    ports:
      - 5000:5000
    command: --tlsextradomain=lnd-alice

  lnd-bob:
    restart: unless-stopped
    image: lightninglabs/lnd:v0.14.3-beta
    depends_on:
      - bitcoind
    ports:
      - 5001:5000
    volumes:
      - ./lnd.conf:/root/.lnd/lnd.conf
      - lnd-bob:/cfg
    command: --tlsextradomain=lnd-bob

  loadtest:
    build: loadtest
    depends_on:
      - lnd-alice
      - lnd-bob
    volumes:
      - lnd-alice:/lnd-alice
      - lnd-bob:/lnd-bob
      - ./${LOADTEST_CONFIG_FILE}:/loadtest.yml

volumes:
  lnd-alice:
  lnd-bob:
    